create table if not exists stamp_rally_spots (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  code              varchar(50) not null unique,
  name                        varchar(200),
  yomigana                    varchar(200),
  latitude                    double precision not null,
  longitude                   double precision not null,
  type_register_stamp         varchar(20) not null check (type_register_stamp in ('gps', 'qr', 'gpsDate', 'sample')),
  detail_url                  varchar(500),
  gps_meter                   integer default 0,
  img                         varchar(200),
  stamp_rally_event_id        BIGINT references stamp_rally_events(id),
  created_at                  timestamp with time zone default now(),
  updated_at                  timestamp with time zone default now()
);

-- トリガーで updated_at を自動更新
create or replace function set_updated_at()
returns trigger as $$
begin
  new.updated_at = now();
  return new;
end;
$$ language plpgsql;

create trigger update_stamp_rally_spots_updated_at
before update on stamp_rally_spots
for each row
execute function set_updated_at();