create table if not exists prizes (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  stamp_rally_event_id        BIGINT not null references stamp_rally_events(id),
  name                        varchar(200),
  description                 varchar(1000),
  image_url                   varchar(300),
  created_at                  timestamp with time zone default now(),
  updated_at                  timestamp with time zone default now()
);

-- トリガーで updated_at を自動更新
create or replace function set_updated_at()
returns trigger as $$
begin
  new.updated_at = now();
  return new;
end;
$$ language plpgsql;

create trigger update_prizes_updated_at
before update on prizes
for each row
execute function set_updated_at(); 