create table if not exists worship_cards (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  stamp_rally_spots_id                    BIGINT not null references stamp_rally_spots(id),
  proverbs                    varchar(512),
  top_image_url               varchar(1024),
  main_image_url              varchar(1024),
  created_at                  timestamp with time zone default now(),
  updated_at                  timestamp with time zone default now()
); 

-- トリガーで updated_at を自動更新
create or replace function set_updated_at()
returns trigger as $$
begin
  new.updated_at = now();
  return new;
end;
$$ language plpgsql;

create trigger update_worship_cards_updated_at
before update on worship_cards
for each row
execute function set_updated_at(); 