create table if not exists stamp_rally_events (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  code              varchar(50) not null unique,
  title             varchar(100) not null,
  description          varchar(1000),
  position             varchar(100),
  place_data_list_csv  varchar(300),
  main_image         varchar(300),
  start_date DATE,
  end_date DATE,
  status           varchar(20) not null check (status in ('notActive','active', 'ended')),
  map_type           varchar(20) not null check (map_type in ('normal', 'google')),
  created_at        timestamp with time zone default now(),
  updated_at        timestamp with time zone default now()
);


-- トリガーで updated_at を自動更新（任意）
create or replace function set_updated_at()
returns trigger as $$
begin
  new.updated_at = now();
  return new;
end;
$$ language plpgsql;

create trigger update_stamp_rally_events_updated_at
before update on stamp_rally_events
for each row
execute function set_updated_at();